<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    <ItemGroup>
      <Content Include="ci\cache.json" />
      <Compile Include="ci\Spec.fs" />
      <Compile Include="ci\lib\GhClient.fs" />
      <Compile Include="ci\lib\Electron.fs" />
      <Compile Include="ci\lib\GitNet.fs" />
      <Compile Include="ci\lib\Workers.fs" />
      <Compile Include="ci\lib\TargetOperators.fs" />
      <Compile Include="ci\Build.fs" />
      <Content Include="ci\README.md" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="EasyBuild.FileSystemProvider" Version="1.1.0" />
      <PackageReference Include="EasyBuild.Tools" Version="5.0.1" />
      <PackageReference Include="Fake.Api.GitHub" Version="6.1.4" />
      <PackageReference Include="Fake.Core.Target" Version="6.1.4" />
      <PackageReference Include="Fake.Core.UserInput" Version="6.1.4" />
      <PackageReference Include="Fake.DotNet.Cli" Version="6.1.4" />
      <PackageReference Include="Fake.DotNet.Fsdocs" Version="6.1.4" />
      <PackageReference Include="Fake.JavaScript.Npm" Version="6.1.4" />
      <PackageReference Include="Fake.Tools.Git" Version="6.1.4" />
      <PackageReference Include="Partas.GitNet" Version="2.0.4" />
        <PackageReference Include="FSharp.Core" Version="10.0.100" />
        <PackageReference Update="FSharp.Core" Version="10.0.100" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="src\ElectronApi.Json.Parser\ElectronApi.Json.Parser.fsproj" />
    </ItemGroup>
</Project>
