<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <FablePackageType>library</FablePackageType>
        <OutputType>Library</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <IsPackable>true</IsPackable>
        
        <PackageId>Fable.Electron.Forge</PackageId>
        <Title>Fable.Electron.Forge</Title>
        <RootNamespace>Fable.Electron</RootNamespace>
        <AssemblyName>Fable.Electron.Forge</AssemblyName>
        <Company>Fable-Hub</Company>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/fable-hub/fable-electron</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>Fable;F#;FSharp;Electron;Bindings;Native;JavaScript;JS;fable-javascript</PackageTags>
        <Authors>Shayan Habibi and Contributors</Authors>
        <Copyright>Copyright (c) 2025 Shayan Habibi and Fable-Hub contributors</Copyright>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageVersion>6.0.0</PackageVersion>
        <Version>6.0.0</Version>
        <GitNetInitialVersion>0.1.0</GitNetInitialVersion>
        <PackageIcon>feleico-dark.png</PackageIcon>

    </PropertyGroup>

    <ItemGroup>
        <None Include="../../README.md" Pack="true" PackagePath="\" />
        <None Include="../../docs/static/img/feleico-dark.png">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
            <Link>Public/icon.png</Link>
        </None>
        <Compile Include="Program.fs" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Fable.Core" Version="5.0.0-beta.1" />
        <PackageReference Include="Fable.Package.SDK" Version="1.3.2">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

</Project>
