module Spec

open System
open System.IO
open System.Text.Json
open Partas.GitNet
open Partas.Tools.SepochSemver
open Partas.TypeProvider.BuildHelper
open Partas.Build
open Partas.Build.ErrorHandling
open Partas.TypeProvider.BuildHelper.Runtime.Project

//%FileProvider%START%
[<Literal>]
let __ROOT_DIRECTORY__ = __SOURCE_DIRECTORY__ + "/.."
/// Files/paths that are not guaranteed (may be cleaned out of existence)
[<Literal>]
let __VIRTUAL_DIRECTORY__ = "
    fsdocs/
    temp/
        electron-api.json
    ci/
        cache.json
    bin/
"
/// Type provider which provides design time hints for runtime values
type Repo = BuildHelperProvider<__ROOT_DIRECTORY__, __VIRTUAL_DIRECTORY__, capabilityFullOverride = true>
//%FileProvider%END%

/// The shape of data returned from <c>gh</c> cli when we request release info in json
[<Struct>]
type ReleaseInfo = {
    createdAt: System.DateTime
    isLatest: bool
    isPrerelease: bool
    tagName: string
}
/// <c>&lt;owner>/&lt;repo_name></c>
[<Struct>]
type Repository = {
    Owner: string
    Name: string
}
/// <summary>Flags that modify the execution of downloading assets using the <c>gh</c> cli</summary>
type DownloadFlags = {
    Overwrite: bool
    SkipExisting: bool
    Output: string option
}
/// <summary>
/// The set of options for executing a download using <c>gh</c> cli
/// </summary>
type DownloadArgs = {
    Repository: Repository
    Release: ReleaseInfo option
    Pattern: string list
    Directory: string option
    Flags: DownloadFlags
}
/// <summary>
/// The set of options for creating a pr using the <c>gh</c> cli
/// </summary>
type PrCreateArgs =
    { Assignee: string list
      Base: string option
      Body: string option
      BodyFile: string option
      Draft: bool
      DryRun: bool
      Fill: bool
      FillFirst: bool
      FillVerbose: bool
      Head: string option
      Label: string list
      Milestone: string option
      NoMaintainerEdit: bool
      Project: string list
      Recover: string option
      Reviewer: string list
      Template: string option
      Title: string option
      Repo: Repository }

    static member Init =
        { Assignee = []
          Base = None
          Body = None
          BodyFile = None
          Draft = false
          DryRun = false
          Fill = false
          FillFirst = false
          FillVerbose = false
          Head = None
          Label = []
          Milestone = None
          NoMaintainerEdit = false
          Project = []
          Recover = None
          Reviewer = []
          Template = None
          Title = None
          Repo = { Owner = ""; Name = "" } }

module Versions =
    /// The calculated change in version of a semver
    type DeltaKind =
        | Major
        | Minor
        | Patch
        | Equal
    /// The conventional commit message for a CI generation of the given delta kind.
    let makeCommitMessage message =
        function
        | Major -> "feat!: " + message
        | Minor -> "feat: " + message
        | Patch -> "fix: " + message
        | Equal -> "chore: " + message
        >> fun message ->
            [
                message
                ""
                "This commit is automatically generated by the Fable.Electron CI."
                ""
                "generated: true"
            ]
            |> String.concat "\n"
//%ElectronDeltaTypes%START%
/// <summary>
/// The different version sources used when calculating
/// the semver change type and value for electron.
/// </summary>
type ElectronDeltaVersions = {
    /// <summary>
    /// Our <c>Fable.Electron</c> version (the nuget value)
    /// </summary>
    FableElectronPackage: Semver.SemVersion voption
    /// <summary>
    /// The version of electron that <c>Fable.Electron</c>
    /// was calculated against (can be different to our nuget version).
    /// </summary>
    FableElectronElectron: Semver.SemVersion voption
    /// <summary>
    /// The version of electron that we have in ci/cache.json
    /// </summary>
    CachedElectron: Semver.SemVersion voption
    /// <summary>
    /// The version of electron we have downloaded to generate against.
    /// </summary>
    DownloadedElectron: Semver.SemVersion voption
}

/// <summary>
/// Vectors of semver version for electron
/// </summary>
type ElectronDelta = {
    Versions: ElectronDeltaVersions
    Dirty: bool
    Major: int
    Minor: int
    Patch: int
}
//%ElectronDeltaTypes%END%

//%Projects%START%
module Projects =
    let allProjects = Repo.Project.AllProjects()
    /// Only projects located under src/
    let srcProjects = allProjects |> List.filter _.RelativePath.Contains("src")
    /// Only projects located under tests/
    let testProjects = allProjects |> List.filter _.RelativePath.Contains("tests")
    /// Only projects with 'Fable' in their name
    let fableProjects = allProjects |> List.filter _.Name.Contains("Fable")
    /// Only the docs project
    let docs = allProjects |> List.find _.Name.Equals("Docs")
    /// Only the build project
    let build = allProjects |> List.find _.Name.Equals("Build")
//%Projects%END%

module GitNet =
    /// Configuration for GitNet
    let config = {
        GitNetConfig.initFSharp with
            RepositoryPath = Repo.FileSystem.``.``.FullName
//%GitNetIgnore%START%
            // These are the projects that are ignored for versioning
            // The GitNet system won't bother matching commits to files under their directories
            Projects.IgnoredProjects = Projects.allProjects |> List.except Projects.srcProjects |> List.map _.Name
//%GitNetIgnore%END%
            // Whether gitnet should generate assembly files
            AssemblyFiles = AssemblyFileManagement.None
            // Whether gitnet should write updated versions to the project files directly
            WriteVersionToProjects = true
//%GitNetBumps%START%
            Bump.DefaultBumpStrategy = ForceBumpStrategy.All
            // When you make a conventional commit the type is the first verb/adjective: "<type>[(<scope>)]: <summary>"
            // GitNet will match commits to the 'type' of bump they should cause.
            // There are different matching methods, the easiest to use is the 'type'.
            Bump.Mapping.Major =
                // This means any conventional commit starting with "breaking" or "remove" will cause
                // a major bump for the projects that had modified files in that commit
                [ BumpMatcher.Type "breaking"; BumpMatcher.Type "remove" ]
            Bump.Mapping.Minor = [ BumpMatcher.Type "feat"; BumpMatcher.Type "new"; BumpMatcher.Type "add" ]
            Bump.Mapping.Patch = [ BumpMatcher.Type "fix"; BumpMatcher.Type "update"; BumpMatcher.Type "change" ]
//%GitNetBumps%END%
            // Whether the output changelog/release-notes will include non-conventional commits
            Output.AllowUnconventional = false
            // The output changelog/release-notes groups commits into different categories.
            // This is where that is controlled
            Output.GroupMatcher = [
                GroupMatcher(CommitGroup.Defaults.breaking, [ BumpMatcher.Type "breaking" ])
                GroupMatcher(CommitGroup.Defaults.changed, [ BumpMatcher.Type "update"; BumpMatcher.Type "change" ])
                GroupMatcher(CommitGroup.Defaults.deprecated, [
                    BumpMatcher.Type "depr"
                    BumpMatcher.Type "deprecated"
                    BumpMatcher.Type "deprecate"
                ])
                GroupMatcher(CommitGroup.Defaults.feat, [
                    BumpMatcher.Type "feat"
                    BumpMatcher.Type "enhancement"
                    BumpMatcher.Type "new"
                    BumpMatcher.Type "added"
                ])
                GroupMatcher(CommitGroup.Defaults.fix, [ BumpMatcher.Type "fix"; BumpMatcher.Type "fixed" ])
                GroupMatcher(CommitGroup.Defaults.revert, [
                    BumpMatcher.Type "rollback"
                    BumpMatcher.Type "revert"
                    BumpMatcher.Type "rev"
                ])
                GroupMatcher(CommitGroup.Defaults.changed, [
                    BumpMatcher.Type "updated"
                    BumpMatcher.Type "update"
                    BumpMatcher.Type "change"
                ])
            ]
            // Whether commits that don't match into a group from above will be included IN THE OUTPUT
            Output.AllowUnmatched = true
            // Any commit that doesn't match into a group from above will fall back into this group
            Output.DefaultUnmatchedGroup = CommitGroup.Defaults.other
            // Any commit that matches against the filters here will be ignored IN THE OUTPUT
            Output.Ignore = [
                IgnoreCommit.FooterKeyValue("changelog", "true")
                IgnoreCommit.FooterKeyValue("gitnet", "ignore")
                IgnoreCommit.SkipCi
            ]
    }
//%GitNetInit%START%
    let runtime = Producer.emptyDefine "initial runtime" (new GitNetRuntime(config) |> Operation.ret)
    /// We do a gitnet dry run - this doesn't write any versions to files, make any commits/tags etc
    /// and provides us the calculated changes that would have occurred
    let initialCompute = DependencySpec.require runtime |> DependencySpec.map _.DryRun()
//%GitNetInit%END%
    let private getInitialVersion scope =
        initialCompute
        |> DependencySpec.map (fun initialCompute ->
            match initialCompute.Versions.TryGetValue scope  with
            | true, semver -> semver |> ValueOption.bind GitNetTag.chooseSemverCompatible
            | _ -> ValueNone
        )
    let private getInitialBump scope =
        initialCompute
        |> DependencySpec.map (fun initialCompute ->
            match initialCompute.Bumps.TryGetValue scope with
            | true, semver -> ValueSome semver
            | _ -> ValueNone
        )
    let private getInitial scope =
        (getInitialVersion scope, getInitialBump scope)
        ||> DependencySpec.map2 (fun initial bump -> {| version = initial; bump = bump |})
    /// The computed version and bump for Fable.Electron.Forge with the current
    /// git commit history (BEFORE any CI operation has run)
    let initForge = getInitial "Forge"
    /// The computed version and bump for Fable.Electron with the current
    /// git commit history (BEFORE any CI operation has run)
    let initElectron =
        getInitialBump "Electron"
        |> DependencySpec.map (fun bump ->
            {|
                version =
                    match Semver.SemVersion.TryParse Repo.Project.``Fable.Electron``.Version with
                    | true, version -> Some version
                    | _ -> None
                bump = bump
            |}
        )
    /// The computed version and bump for Fable.Electron.Remoting with the current
    /// git commit history (BEFORE any CI operation has run)
    let initRemoting = getInitial "Remoting"
    let private _initSpecs =
        (initForge, initRemoting)
        ||> DependencySpec.map2(fun f r -> {| forge = f; remoting = r |})
    let initSpecs =
        (_initSpecs, initElectron)
        ||> DependencySpec.map2 (fun specs e -> {| forge = specs.forge; remoting = specs.remoting; electron = e |})

    /// Creates a fresh gitnet runtime.
    let createRuntime() = new GitNetRuntime(config)


module Repository =
    let getReleaseList repo =
        cmd $"gh release list -R {repo.Owner}/{repo.Name} --json tagName,createdAt,isLatest,isPrerelease"
        |> executeCapture
        |> Operation.map (fun result ->
            result.Stdout
            |> JsonSerializer.Deserialize<ReleaseInfo[]>
            |> Array.toList
        )
    let downloadReleaseAsset (args: DownloadArgs -> DownloadArgs) =
        let args = args {
            Repository = { Owner = ""; Name = "" }
            Release = None
            Pattern = []
            Directory = None
            Flags = {
                Overwrite = false
                SkipExisting = false
                DownloadFlags.Output = None
            }
        }
        let hasRepositoryValue =
            args.Repository
            |> function { Owner = ""; Name = "" } -> false | _ -> true
        Cmd.create "gh" "release download"
        |> Cmd.argWhenSome args.Release (_.tagName >> List.singleton)
        |> Cmd.argIf hasRepositoryValue [ "-R" ;$"{args.Repository.Owner}/{args.Repository.Name}" ]
        |> Cmd.args (args.Pattern |> List.collect (fun p -> [ "-p"; p ]))
        |> Cmd.argWhenSome args.Directory (fun dir -> [ "--dir"; dir])
        |> Cmd.argWhenSome args.Flags.Output (fun o -> [ "--output"; o ])
        |> Cmd.argIf args.Flags.Overwrite [ "--clobber" ]
        |> Cmd.argIf args.Flags.SkipExisting [ "--skip-existing" ]
        |> execute
    /// Create a PR using the given options asynchronously through the gh/github cli
    let createPr (args: PrCreateArgs -> PrCreateArgs) =
        let this = args PrCreateArgs.Init
        let hasRepositoryValue =
            this.Repo
            |> function { Owner = ""; Name = "" } -> false | _ -> true
        Cmd.create "gh" "pr create"
        |> Cmd.argIf (not this.Assignee.IsEmpty) [ "--assignee"; this.Assignee |> String.concat "," ]
        |> Cmd.argWhenSome this.Base (fun b -> [ "--base"; b ])
        |> Cmd.argWhenSome this.BodyFile (fun bodyFile -> [ "--body-file"; bodyFile ])
        |> Cmd.argIf this.Draft [ "--draft" ]
        |> Cmd.argIf this.DryRun [ "--dry-run" ]
        |> Cmd.argIf this.Fill [ "--fill" ]
        |> Cmd.argIf this.FillFirst [ "--fill-first" ]
        |> Cmd.argIf this.FillVerbose [ "--fill-verbose" ]
        |> Cmd.argWhenSome this.Head (fun head -> [ "--head"; head ])
        |> Cmd.args (this.Label |> List.collect (fun l -> [ "--label"; l ]))
        |> Cmd.argWhenSome this.Milestone (fun milestone -> [ "--milestone"; milestone ])
        |> Cmd.argIf this.NoMaintainerEdit [ "--no-maintainer-edit" ]
        |> Cmd.argIf (not this.Project.IsEmpty) [ "--project"; this.Project |> String.concat "," ]
        |> Cmd.argWhenSome this.Recover (fun recover -> [ "--recover"; recover ])
        |> Cmd.argIf (not this.Reviewer.IsEmpty) [ "--reviewer"; this.Reviewer |> String.concat "," ]
        |> Cmd.argWhenSome this.Template (fun template -> [ "--template"; template ])
        |> Cmd.argWhenSome this.Title (fun title -> [ "--title"; title ])
        |> Cmd.argIf hasRepositoryValue [ "--repo"; $"{this.Repo.Owner}/{this.Repo.Name}" ]
        |> execute

module Electron =
    let repo = {
        Owner = "electron"
        Name = "electron"
    }
    /// Asynchronously get the electron release list
    let getReleases = Repository.getReleaseList repo |> Producer.emptyDefine "get release list"
    /// Asynchronously download the electron api json for the given release
    let downloadElectronApi overwrite outputFile release =
        Repository.downloadReleaseAsset (fun args -> {
            args with
                Repository = repo
                Pattern = [ "electron-api.json" ]
                Release = Some release
                Flags.Output = Some outputFile
                Flags.SkipExisting = not overwrite
                Flags.Overwrite = overwrite
        })

//%ElectronDeltaRules%START%
module ElectronDelta =
    /// Determine the delta kind from a given electron delta
    let deltaKind = function
        | { Major = 0; Minor = 0; Patch = 0 } -> Versions.Equal
        | { Major = 0; Minor = 0 } -> Versions.Patch
        | { Major = 0 } -> Versions.Minor
        | _ -> Versions.Major
    /// Whether the electron delta represents a bump of any kind (patch/minor/major etc)
    let isBump = deltaKind >> _.IsEqual >> not
    /// Whether the electron delta is calculated from a run that occurred outside
    /// the current branch it is running in
    let isProbablyPulled delta =
        let deltaKind = deltaKind delta
        let cachedVersion =
            delta.Versions.CachedElectron
            |> ValueOption.defaultValue (Semver.SemVersion(0,1,0))
        let currentVersion =
            delta.Versions.FableElectronElectron
            |> ValueOption.defaultValue (Semver.SemVersion(0,1,0))
        deltaKind.IsMajor
        && currentVersion.ComparePrecedenceTo(cachedVersion) > 0
    /// What the next tag/version we release for electron. Remembering that
    /// any time we need to release a change for a given electron version, it will
    /// result in only a patch bump. Otherwise, the version follows the electron version
    /// it was generated from.
    let nextElectronVersion delta =
        let deltaKind = deltaKind delta
        let makeSepochSemver = fun semver ->
            {
                SemVer = ValueOption.defaultValue (Semver.SemVersion(0,1,0)) semver
                Sepoch = Sepoch.Scope "Electron"
            }
        match delta, deltaKind with
        | _, (Versions.Major | Versions.Minor) -> delta.Versions.DownloadedElectron |> makeSepochSemver
        | _, Versions.Patch
        | { Dirty = true }, _ -> delta.Versions.FableElectronPackage |> makeSepochSemver |> SepochSemver.bumpPatch
        | _ -> delta.Versions.FableElectronPackage |> makeSepochSemver
//%ElectronDeltaRules%END%

/// CLI flags/options for running operations in this repository/project
module Options =
//%Options%START%
    let quick =
        Input.option<bool> "--quick"
        |> Input.alias "-q"
        |> Input.desc "Skips installation, cleaning, and/or download steps."
    let release =
        Input.optionMaybe<string> "--release"
        |> Input.desc "Specify the release to target for this action."
        |> Input.arity ExactlyOne
        |> InputSpec.ofInput
        |> InputSpec.map (Option.map Semver.SemVersion.Parse)
//%Options%END%
    let cache =
        Input.option<bool> "--cache-release"
        |> Input.desc "Target the release specified in the cache"
    let watch =
        Input.option<bool> "--watch"
        |> Input.alias "-w"
        |> Input.desc "Run the operation in watch mode."
    let openFlag =
        Input.option<bool> "--windowed"
        |> Input.desc "Open the test project as an electron application"
    let npmCi =
        Input.option<bool> "--clean-install"
        |> Input.alias "--npm-ci"
        |> Input.desc "Install operations with npm are performed using --clean-install"
    let config =
        Baked.Dotnet.config.option
        |> Input.desc "The build configuration; defaults to Release."
        |> InputSpec.ofInput
        |> InputSpec.map (Option.defaultValue "Release")
    let allProjectTargets =
        Input.option<ProjectRef list> "--project"
        |> Input.alias "-p"
        |> Input.desc "Project(s) to target with operation. Defaults depend on operation in question, but will be some subset of all projects."
        |> Input.mapFromManyWith StringComparer.OrdinalIgnoreCase (
            Projects.allProjects
            |> List.map (fun project ->
                project.Name, project
            )
            )
        |> Input.arity OneOrMore
        |> Input.allowMultipleArgumentsPerToken
        |> Input.def []
    let concurrent =
        Input.option<bool> "--parallel"
        |> Input.def true
        |> Input.desc "Whether to perform operations in parallel"
    let patchOnly =
        Input.option<bool> "--only-patch"
        |> Input.desc "Only consider releases that are a patch of the cached release."
    let minorOnly =
        Input.option<bool> "--only-minor"
        |> Input.desc "Only consider releases that are a minor of the cached release."
    let dryRun =
        Input.option<bool> "--dry-run"
        |> Input.desc "Print the git, nuget and github actions the run would take instead of performing them."
    let ghKey =
        Input.optionMaybe<string> "--gh-key"
        |> Input.desc "GitHub token for the gh cli; defaults to the GH_TOKEN/GITHUB_TOKEN environment."

module Inputs =
    /// Reads and returns the cached release info
    let cache =
        Operation.ofAsync (async {
            if Repo.VirtualFileSystem.ci.``cache.json``.Exists |> not then return None else
            return
                File.ReadAllText Repo.VirtualFileSystem.ci.``cache.json``.FullName
                |> JsonSerializer.Deserialize<ReleaseInfo>
                |> Some
        })
        |> Producer.emptyDefine "fetch cache"
//%ReleaseProducer%START%
    /// asynchronously retrieves the release info for either the requested release/bump type
    /// from the electron repo using the gh cli. consider this to be the requested release info
    /// we are generating against. Falls back to the 'latest' release if none are specifically
    /// requested.
    let release =
        Producer.define
            "release"
            (input {
                let! release = Options.release
                and! patchOnly = Options.patchOnly
                and! minorOnly = Options.minorOnly
                and! cacheRelease = Options.cache
                return {| release = release; patchOnly = patchOnly; minorOnly = minorOnly; cacheRelease = cacheRelease |}
            })
            (DependencySpec.zip cache Electron.getReleases)
            (fun inputs (cache, releases) ->
                let cache = cache |> Option.map (_.tagName.Trim('v') >> Semver.SemVersion.Parse)
                if (inputs.patchOnly || inputs.minorOnly) && cache.IsNone then
                    failwith "--only-minor && --only-patch can only be used when there is a cached release value. \
                            Either specify a release to operate on with --release or allow the latest release to download"
                elif inputs.cacheRelease && cache.IsNone then
                    failwith "--cache-release can only be used when there is a cached release object @ /ci/cache.json"
                else
                Operation.ofAsync (async {
                return releases
                |> List.filter (_.isPrerelease >> not)
                |> List.filter (fun info ->
                    let value = Semver.SemVersion.Parse(info.tagName.Trim('v'))
                    match inputs.release, cache with
                    | Some requested, _ -> value = requested
                    | None, Some cached when inputs.cacheRelease -> value = cached
                    | None, Some cached when inputs.minorOnly && inputs.patchOnly ->
                        value.Major = cached.Major
                        && (value.Minor > cached.Minor || (value.Minor = cached.Minor && value.Patch > cached.Patch))
                    | None, Some cached when inputs.patchOnly ->
                        value.Major = cached.Major && value.Minor = cached.Minor && value.Patch > cached.Patch
                    | None, Some cached when inputs.minorOnly ->
                        value.Major = cached.Major && value.Minor > cached.Minor
                    | _ -> info.isLatest
                )
                |> function
                    | [] when inputs.release.IsSome ->
                        failwith $"Unable to find the specified release {inputs.release.Value}"
                    | [] -> None
                    | values -> List.maxBy _.createdAt values |> Some
                })
            )
//%ReleaseProducer%END%
    /// Asynchronously downloads the electron api file for the requested release
    let downloadApi =
        Producer.define
            "download api"
            InputSpec.empty
            (DependencySpec.require release)
            (fun () -> function
                | Some release ->
                    Electron.downloadElectronApi
                        true
                        Repo.VirtualFileSystem.temp.``electron-api.json``.FullName
                        release
                | None -> Operation.ret ()
            )

    /// Asynchronously calculates the electron delta versions using the
    /// requested release, cache, and project values
    let electronDeltaVersions =
        DependencySpec.zip cache release
        |> DependencySpec.map (fun (cache,release) ->
            {
                FableElectronPackage =
                    match Repo.Project.``Fable.Electron``.Version with
                    | "" -> ValueNone
                    | version -> Semver.SemVersion.Parse version |> ValueSome
                FableElectronElectron =
                    match Repo.Project.``Fable.Electron``.Property("ElectronVersion") with
                    | "" -> ValueNone
                    | version -> Semver.SemVersion.Parse version |> ValueSome
                CachedElectron =
                    cache
                    |> Option.map (
                        _.tagName.Trim('v')
                        >> Semver.SemVersion.Parse
                        )
                    |> Option.toValueOption
                DownloadedElectron =
                    release
                    |> Option.map (
                        _.tagName.Trim('v')
                        >> Semver.SemVersion.Parse
                        )
                    |> Option.toValueOption
            }
        )

    /// Checks whether the generated file is modified using git
    let electronIsDirty() =
        let fileIsDirty file =
            Repo.Git.Run($"status -s -- {file}")
            |> function
                | "" -> false
                | v -> true
        Repo.Git.IsDirty()
        && fileIsDirty Repo.FileSystem.src.``Fable.Electron``.``Program.fs``
    /// calculated electron delta versions at request time
    let electronDelta =
        electronDeltaVersions
        |> DependencySpec.map  (fun deltaVersions ->
            let defaultInt = ValueOption.defaultValue 0
            let deltaPath (path: Semver.SemVersion -> bigint) =
                (deltaVersions.DownloadedElectron
                |> ValueOption.map (path >> int)
                |> defaultInt) - (
                deltaVersions.FableElectronElectron
                |> ValueOption.map (path >> int)
                |> defaultInt
                )
            {
                Versions = deltaVersions
                Dirty = electronIsDirty()
                Major = deltaPath _.Major
                Minor = deltaPath _.Minor
                Patch = deltaPath _.Patch
            }
        )

    let initialGitStatus =
        (electronDelta, GitNet.initSpecs)
        ||> DependencySpec.map2 (fun electronDelta specs ->
            let forge, remoting = specs.forge, specs.remoting
            let anyPackageUpdated =
                forge.bump.IsSome
                || remoting.bump.IsSome
                || ElectronDelta.isBump electronDelta
            let requiresPull =
                not (ElectronDelta.isProbablyPulled electronDelta)
                && (ElectronDelta.deltaKind electronDelta).IsMajor
            {| delta = electronDelta; forge = forge; remoting = remoting; anyPackageUpdated = anyPackageUpdated; requiresPull = requiresPull  |}
        )

/// The versioning, commit, tag and pull request flow at the end of a scheduled generation.
module Release =
    [<CLIMutable>]
    type PullRequestInfo = {
        reviewers: string array
        labels: string array
        projects: string array
        assignees: string array
    }
    /// The reviewers, labels, projects and assignees a generated pull request carries, from <c>ci/pull_request.json</c>.
    let pullRequestInfo () =
        try
            Repo.FileSystem.ci.``pull_request.json``.FullName
            |> File.ReadAllText
            |> JsonSerializer.Deserialize<PullRequestInfo>
        with _ -> { reviewers = [||]; labels = [||]; projects = [||]; assignees = [||] }
    /// Sets one MSBuild property in the first property group of the project file.
    let writeProjectProperty (project: ProjectRef) (name: string) (value: string) =
        let document = System.Xml.Linq.XDocument.Load(project.Path, System.Xml.Linq.LoadOptions.PreserveWhitespace)
        let group = document.Root.Elements(System.Xml.Linq.XName.Get "PropertyGroup") |> Seq.head
        Baked.IO.writeProperty group name (fun _ -> value) |> ignore
        Baked.IO.save project.Path document
    let private project name = Projects.srcProjects |> List.find _.Name.Equals(name: string)
    let electron = project "Fable.Electron"
    let forge = project "Fable.Electron.Forge"
    let remoting = project "Fable.Electron.Remoting"
    /// The branch a generation of the given release lands on when it requires a pull request.
    let branchFor (release: ReleaseInfo) = $"ci/electron/{release.tagName}"
    /// The files the generation touches, relative to the repository root: the packable projects, their
    /// compiled sources, and the cache.
    let generatedFiles () =
        let root = Repo.FileSystem.``.``.FullName
        let compiledFiles (project: ProjectRef) =
            let document = System.Xml.Linq.XDocument.Load project.Path
            document.Descendants(System.Xml.Linq.XName.Get "Compile")
            |> Seq.choose (fun element -> element.Attribute(System.Xml.Linq.XName.Get "Include") |> Option.ofObj)
            |> Seq.map (fun attribute -> Path.Combine(project.Directory, attribute.Value))
            |> Seq.filter File.Exists
            |> List.ofSeq
        [ electron; forge; remoting ]
        |> List.collect (fun project -> project.Path :: compiledFiles project)
        |> List.append [ Repo.VirtualFileSystem.ci.``cache.json``.FullName ]
        |> List.map (fun path -> Path.GetRelativePath(root, path).Replace('\\', '/'))
    /// The title and body of the pull request for a generated release, with the generation failures when
    /// there were any.
    let pullRequestText (release: ReleaseInfo) (failures: string list) =
        match failures with
        | [] ->
            $"Electron {release.tagName}",
            $"""Bindings for electron {release.tagName} were generated successfully and passed tests.

This electron release was created on {release.createdAt}.

Once this pull is merged into `main`, publishing will occur. It is recommended to merge into `develop` for major electron versions first.
"""
        | failures ->
            let details =
                failures
                |> List.map (fun failure -> $"<details>\n<summary>Error</summary>\n\n```\n{failure}\n```\n\n</details>")
                |> String.concat "\n"
            $"[GEN ERROR] For Electron {release.tagName}",
            $"""During the build process, I came across some errors. Once corrected, please consider merging into `develop`.

{details}"""

module Stage =
    let checkElectronRepoHealth = stage "check electron repo connection" {
        runHttpHealthCheck $"https://github.com/{Electron.repo.Owner}/{Electron.repo.Name}"
    }
    let private deleteDirectory (path: string) =
        if Directory.Exists path then Directory.Delete(path, true)
    /// Clean the temp/ directory
    let cleanTemp = input {
        let! quick = Options.quick
        return stage "clean-temp" {
            when' (not quick)
            run (fun _ -> deleteDirectory Repo.VirtualFileSystem.temp.``.``.FullName)
        }
    }
    /// Clean the bin/ and obj/ directories of every project other than this one
    let clean = input {
        let! quick = Options.quick
        and! cleanTemp = cleanTemp
        return stage "clean" {
            when' (not quick)
            parallel'
            cleanTemp
            run (fun _ ->
                Projects.allProjects
                |> List.except [ Projects.build ]
                |> List.iter (fun project ->
                    deleteDirectory (Path.Combine(project.Directory, "bin"))
                    deleteDirectory (Path.Combine(project.Directory, "obj"))
                )
            )
        }
    }
    /// Clean any generated fable files.
    /// Only operates in fable project directories outside tests/.
    let cleanFable = input {
        let! quick = Options.quick
        return stage "clean-fable" {
            when' (not quick)
            parallel'
            for project in Projects.fableProjects |> List.except Projects.testProjects do
            stage $"clean-{project.Name}" {
                workingDir project.Directory
                run "dotnet fable clean -e .js --yes"
            }
        }
    }
    /// runs dotnet tool restore
    let restoreTools = input {
        let! quick = Options.quick
        return stage "restore-tools" {
            when' (not quick)
            run "dotnet tool restore"
        }
    }
    let private npmInstall (cleanInstall: bool) = Cmd.create "npm" (if cleanInstall then "clean-install" else "install")
    /// Performs npm install operations for tests
    let installTests = input {
        let! cleanInstall = Options.npmCi
        and! quick = Options.quick
        return stage "test install" {
            workingDir Repo.Project.``Fable.Electron.Remoting.Tests``.Directory
            when' (not quick)
            run (npmInstall cleanInstall)
        }
    }
    /// Installs npm tests, and runs them.
    /// Can optionally run the tests in watch mode, or open the electron application window.
    let runTest = input {
        let! installTests = installTests
        and! watch = Options.watch
        and! windowed = Options.openFlag
        return stage "test" {
            installTests
            stage "npm run" {
                workingDir Repo.Project.``Fable.Electron.Remoting.Tests``.Directory
                run (
                    Cmd.create "npm" "run"
                    |> Cmd.arg (
                        if watch then "watch"
                        elif windowed then "start"
                        else "test"
                        )
                )
            }
        }
    }
//%GenerateStage%START%
    /// Generates the Fable.Electron bindings from temp/electron-api.json, downloading it first when absent
    let generate = stage "generate" {
        consumes (DependencySpec.require Inputs.downloadApi) (fun () ->
            Operation.ofAsync (async {
                let api = Repo.VirtualFileSystem.temp.``electron-api.json``
                if not api.Exists then
                    failwith $"electron API data was not found @ {api.FullName}. Run 'releases download' first, or place the file there."
                ElectronApi.Json.Parser.Generator.Transpiler.generateFromApiFile
                    api.FullName
                    Repo.FileSystem.src.``Fable.Electron``.``Program.fs``.FullName
            })
        )
    }
//%GenerateStage%END%
    /// Prints the versions and bumps the run has calculated
    let echoStatus = stage "status" {
        consumes Inputs.initialGitStatus (fun status ->
            $"
Summary of current status for GitNet:

Electron Cached Version: {status.delta.Versions.CachedElectron.ToString()}
    The electron release recorded in ci/cache.json.

Is Probably Pulled: {ElectronDelta.isProbablyPulled status.delta}
    The cached electron version is ahead of the project file's, so this
    branch was merged from a generated pull.

Current Electron Version: {status.delta.Versions.FableElectronElectron.ToString()}
    The project file electron version. Updated only when merged to main.

Current Package Version: {status.delta.Versions.FableElectronPackage.ToString()}
    The package version of Fable.Electron.

Downloaded Version: {status.delta.Versions.DownloadedElectron.ToString()}
    The version of Electron downloaded in this run.

Delta: {ElectronDelta.deltaKind status.delta}
    A major delta submits a pull instead of publishing.

Next version: {ElectronDelta.nextElectronVersion status.delta |> _.ToString()}

Is Electron Package Updated: {ElectronDelta.isBump status.delta}
    Whether the Electron package changed, from the electron version or the generator.

Is Any Package Updated: {status.anyPackageUpdated}

Next versions:
    Remoting: {status.remoting}
    Forge: {status.forge}

Package Requires Pull: {status.requiresPull}
"
            |> printfn "%s"
            |> Operation.ret
        )
    }
    let private targetProjects (defaults: ProjectRef list) =
        Options.allProjectTargets
        |> InputSpec.ofInput
        |> InputSpec.map (function
            | [] -> defaults
            | projects -> projects
            )
//%BuildStage%START%
    /// Builds projects
    let build = input {
        let! projects = targetProjects Projects.srcProjects
        and! config = Options.config
        and! concurrent = Options.concurrent
        return stage "build" {
            failIfNoActiveSubStage
            parallel' concurrent
            for project in projects do
            stage $"build {project.Name}" {
                when' (File.Exists project.Path)
                run (
                    Cmd.create "dotnet" "build -v q"
                    |> Cmd.args [ "-c"; config ]
                    |> Cmd.arg project.Path
                )
            }
        }
    }
//%BuildStage%END%
    /// Builds fable projects
    let fableBuild = input {
        let! projects =
            Options.allProjectTargets
            |> InputSpec.ofInput
            |> InputSpec.map (function
                | [] -> Projects.fableProjects |> List.filter _.Name.Equals("Fable.Electron")
                | projects ->
                    Set.union (Set.ofList projects) (Set.ofList Projects.fableProjects)
                    |> Set.toList
                )
        and! config = Options.config
        and! concurrent = Options.concurrent
        return stage "fable build" {
            parallel' concurrent
            for project in projects do
            stage project.Name {
                workingDir project.Directory
                run $"dotnet fable -e .js -c {config} --noCache"
            }
        }
    }
    /// Packs projects into /bin/
    let pack = input {
        let! projects = targetProjects Projects.srcProjects
        and! config = Options.config
        and! concurrent = Options.concurrent
        return stage "pack" {
            failIfNoActiveSubStage
            parallel' concurrent
            for project in projects do
            stage $"pack {project.Name}" {
                when' (File.Exists project.Path)
                run (
                    Cmd.create "dotnet" "pack -v q"
                    |> Cmd.args [ "-c"; config ]
                    |> Cmd.arg project.Path
                    |> Cmd.args [ "-o"; Repo.VirtualFileSystem.bin.``.``.FullName ]
                )
            }
        }
    }
    /// Publishes all packed packages in /bin/ to nuget
    let publish = input {
        let! apiKey = Baked.NuGet.apiKey.option
        and! dryRun = Options.dryRun
        return stage "publish" {
            whenSome apiKey (fun key ->
                let cmd =
                    Cmd.create "dotnet" "nuget push"
                    |> Cmd.arg (Path.Combine(Repo.VirtualFileSystem.bin.``.``.FullName, "*.nupkg"))
                    |> Cmd.args [
                        "--source"
                        "https://api.nuget.org/v3/index.json"
                        "--skip-duplicate"
                    ]
                    |> Cmd.secretOption "--api-key" key
                stage "nuget push" {
                    when' (not dryRun)
                    run cmd
                }
            )
            stage "dry run" {
                when' dryRun
                echo "[ACTION] dotnet nuget push bin/*.nupkg"
            }
        }
    }
    /// Formats the source of the given projects with fantomas
    let format = input {
        let! projects = targetProjects (Projects.srcProjects @ Projects.testProjects)
        return stage "format" {
            run (
                Cmd.create "dotnet" "fantomas"
                |> Cmd.args (projects |> List.map _.Directory)
            )
        }
    }
    /// Installs the docs site dependencies
    let installDocs = input {
        let! cleanInstall = Options.npmCi
        and! quick = Options.quick
        return stage "docs install" {
            workingDir Projects.docs.Directory
            when' (not quick)
            run (npmInstall cleanInstall)
        }
    }
    /// Serves the docs site in watch mode
    let serveDocs = stage "docs serve" {
        workingDir Projects.docs.Directory
        run "npm run start"
    }
    /// Authenticates the gh cli for the rest of the process from --gh-key
    let githubAuth = input {
        let! key = Options.ghKey
        return stage "github auth" {
            when' key.IsSome
            run (fun _ -> Environment.SetEnvironmentVariable("GH_TOKEN", Option.defaultValue "" key))
        }
    }
    /// Packs this project as a dotnet tool into /bin/
    let packTool = stage "pack tool" {
        run (
            Cmd.create "dotnet" "pack -v q"
            |> Cmd.arg Projects.build.Path
            |> Cmd.args [ "-o"; Repo.VirtualFileSystem.bin.``.``.FullName ]
        )
        echo """
Tool 'fable-electron' created in '/bin'.
With DotNet 10.0.100+ use `dnx build --source ./bin` to initialise. Afterwards, you can run the build cli using `dnx build`.
Otherwise, you can locally install the tool using `dotnet tool install --source ./bin build`, and run it using `dotnet fable-electron`.

# WARNING - do not commit/push the dotnet-tools.json changes.
"""
    }
//%ReleaseStage%START%
    /// <summary>
    /// The versioning, commit, tag, publish and pull request steps of a scheduled generation, decided from
    /// the status the run calculated before it began.
    /// </summary>
    /// <remarks>
    /// When any package changed, a major electron delta lands on a branch and opens a pull request into
    /// <c>develop</c>; any other delta commits, tags and publishes on the current branch. Failures recorded in
    /// <paramref name="generationFailures"/> put the run on a branch and into the pull request body.
    /// <c>--dry-run</c> prints each git, nuget and github action instead of performing it.
    /// </remarks>
    let release (generationFailures: ResizeArray<string>) = input {
        let! dryRun = Options.dryRun
        and! pack = pack
        and! publish = publish
        let status = DependencySpec.map2 (fun status release -> status, release) Inputs.initialGitStatus (DependencySpec.require Inputs.release)
        let requiresPull (status: {| delta: ElectronDelta; forge: {| version: GitNetTag voption; bump: SepochSemver voption |}; remoting: {| version: GitNetTag voption; bump: SepochSemver voption |}; anyPackageUpdated: bool; requiresPull: bool |}) =
            status.requiresPull || generationFailures.Count > 0
        let git (arguments: string) = Cmd.create "git" arguments
        // Performs the action, or prints it under --dry-run.
        let act (description: string) (perform: unit -> unit) =
            if dryRun then printfn $"[ACTION] {description}" else perform ()
        // Runs the command, or prints it under --dry-run.
        let actCmd (command: Cmd) =
            if dryRun then Operation.ofAsync (async { printfn $"[ACTION] {Cmd.toLogString command}" }) else execute command
        // Packages publish when a package changed and the run stays on its branch.
        let publishable (stage: Partas.Build.Internal.StageContext) =
            match status.Read (StageContext.publishedValues stage) with
            | Ok(status, _) -> status.anyPackageUpdated && not (requiresPull status)
            | Error _ -> false
        let publishPackages =
            stage "publish packages" {
                consumes status (fun _ -> Operation.ret ())
                pack
                publish
            }
            |> StageContext.addPredicateBecause (ValueSome "the run opens a pull request or changes nothing") publishable
        return stage "release" {
            stage "version and commit" {
                consumes status (fun (status, requested) ->
                    match status.anyPackageUpdated, requested with
                    | false, _ -> Operation.ofAsync (async { printfn "No changes during CI." })
                    | true, None -> Operation.fail (FailureCause.Reported "A package changed, but no release was requested or found.")
                    | true, Some release ->
                        let branch = Release.branchFor release
                        let guardBranch =
                            if requiresPull status then
                                executeCapture (git $"ls-remote --heads origin {branch}")
                                |> Operation.bind (fun result ->
                                    if not (String.IsNullOrWhiteSpace result.Stdout) && not dryRun then
                                        Operation.fail (FailureCause.Reported $"A pull already exists for release {release.tagName}.")
                                    else actCmd (git $"checkout -b {branch}"))
                            else Operation.ret ()
                        guardBranch
                        |> Operation.bind (fun () ->
                            Operation.ofAsync (async {
                                let deltaKind = ElectronDelta.deltaKind status.delta
                                let versions = [
                                    Release.electron, ElectronDelta.nextElectronVersion status.delta
                                    match status.forge.bump with
                                    | ValueSome bump -> Release.forge, bump
                                    | ValueNone -> ()
                                    match status.remoting.bump with
                                    | ValueSome bump -> Release.remoting, bump
                                    | ValueNone -> ()
                                ]
                                let commitMessage = Versions.makeCommitMessage $"Electron binding update to match {release.tagName}" deltaKind
                                let runtime = GitNet.createRuntime ()
                                match status.delta.Versions.DownloadedElectron with
                                | ValueSome downloaded ->
                                    act $"Set Fable.Electron ElectronVersion: {downloaded}" (fun () ->
                                        Release.writeProjectProperty Release.electron "ElectronVersion" (downloaded.ToString()))
                                | ValueNone -> ()
                                for project, version in versions do
                                    act $"Set {project.Name} Version: {version.SemVer}" (fun () ->
                                        Release.writeProjectProperty project "Version" (version.SemVer.ToString())
                                        Release.writeProjectProperty project "PackageVersion" (version.SemVer.ToString()))
                                act $"Write to cache: {release}" (fun () ->
                                    File.WriteAllText(Repo.VirtualFileSystem.ci.``cache.json``.FullName, JsonSerializer.Serialize release))
                                let files = Release.generatedFiles ()
                                act $"Stage files: %A{files}" (fun () -> runtime.StageFiles files)
                                act $"Commit with message: {commitMessage}" (fun () -> runtime.CommitChanges(message = commitMessage, appendCommit = false))
                                if not (requiresPull status) then
                                    let tags = versions |> List.map snd
                                    act $"Git tag with: %A{tags |> List.map _.ToString()}" (fun () -> runtime.CommitTags tags)
                                act "Generate release notes, stage and commit" (fun () ->
                                    runtime.DryRun().Markdown |> runtime.WriteToOutputAndStage
                                    runtime.CommitChanges(appendCommit = false))
                            }))
                )
            }
            publishPackages
            stage "push" {
                consumes status (fun (status, requested) ->
                    match requested with
                    | Some release when status.anyPackageUpdated ->
                        executeCapture (git "rev-parse --abbrev-ref HEAD")
                        |> Operation.map _.Stdout.Trim()
                        |> Operation.bind (fun branch ->
                            actCmd (git $"push -u origin {branch}")
                            |> Operation.bind (fun () -> actCmd (git "push --tags origin"))
                            |> Operation.bind (fun () ->
                                if not (requiresPull status) then Operation.ret () else
                                let title, body = Release.pullRequestText release (List.ofSeq generationFailures)
                                let info = Release.pullRequestInfo ()
                                if dryRun then Operation.ofAsync (async { printfn $"[ACTION] Send pull to develop:\n{title}\n\n{body}" }) else
                                Repository.createPr (fun args -> {
                                    args with
                                        Reviewer = List.ofArray info.reviewers
                                        Label = List.ofArray info.labels
                                        Project = List.ofArray info.projects
                                        Assignee = List.ofArray info.assignees
                                        Base = Some "develop"
                                        Head = Some branch
                                        Title = Some title
                                        Body = Some body
                                })))
                    | _ -> Operation.ret ()
                )
            }
        }
    }
//%ReleaseStage%END%

//%GenerationFailures%START%
/// Records the failures of the generation stages ahead of the release, so the pull request can carry them.
let private generationFailures = ResizeArray<string>()
let private recordFailure (context: FailureContext) =
    let nested = context.Nested |> List.collect (fun report -> ScopeReport.failures report |> List.map (fun failure -> report.Name, failure))
    let own = context.Failures |> List.map (fun failure -> context.Scope, failure)
    for scope, failure in own @ nested do
        generationFailures.Add $"{scope}: {FailureCause.describe failure.Cause}"
//%GenerationFailures%END%

//%Cli%START%
[<EntryPoint>]
let main argv = rootCommand argv {
    description "The Fable.Electron build and CI tool"
//%CliBuild%START%
    command "build" {
        description "Build projects"
        Stage.restoreTools
        Stage.clean
        Stage.build
    }
//%CliBuild%END%

    command "test" {
        description "Run the electron test application headless, or with --watch / --windowed"
        Stage.restoreTools
        Stage.runTest
    }

    command "generate" {
        description "Generate the Fable.Electron bindings from the requested electron release"
        Stage.restoreTools
        Stage.generate
        Stage.cleanTemp
    }

    command "pack" {
        description "Pack projects into /bin/"
        Stage.restoreTools
        Stage.build
        Stage.pack
    }

    command "publish" {
        description "Pack projects and push them to nuget with --nuget-key"
        Stage.restoreTools
        Stage.build
        Stage.pack
        Stage.publish
    }

    command "format" {
        description "Format source files with fantomas"
        Stage.restoreTools
        Stage.format
    }

    command "status" {
        description "Show the versions and bumps a run would calculate"
        Stage.echoStatus
    }

    command "fable" {
        description "Operations specifically for fable projects in the repository"
        command "clean" {
            Stage.restoreTools
            Stage.cleanFable
        }
        command "build" {
            Stage.restoreTools
            Stage.cleanFable
            Stage.fableBuild
        }
        command "test" {
            Stage.restoreTools
            Stage.clean
            Stage.cleanFable
        }
    }

    command "releases" {
        description "Shows the releases available"
        Stage.githubAuth
        command "download" {
            Stage.restoreTools
            Producer.stage Inputs.downloadApi
        }
        stage "show releases" {
            consumes (DependencySpec.require Electron.getReleases) (fun releases ->
                releases
                |> List.sortByDescending _.createdAt
                |> List.take 10
                |> List.map (function
                    | { isLatest = true; tagName = tagName; createdAt = createdAt } -> $"[{createdAt.ToShortDateString()}] - {tagName} [LATEST]"
                    | { tagName = tagName; createdAt = createdAt } -> $"[{createdAt.ToShortDateString()}] - {tagName}")
                |> String.concat "\n "
                |> printfn "Releases:\n %s"
                |> Operation.ret
            )
        }
    }

    command "docs" {
        description "Install and serve the docs site"
        Stage.installDocs
        Stage.serveDocs
    }

    command "tool" {
        description "Pack this build project as the 'fable-electron' dotnet tool into /bin/"
        Stage.packTool
    }

//%CliCron%START%
    command "cron" {
        description "The scheduled generation: download the latest release, generate, build, test, then version, commit and publish or open a pull request"
        Stage.githubAuth
        Stage.restoreTools
        Stage.checkElectronRepoHealth
        Producer.stage Inputs.downloadApi
        stage "generation" {
            continueStageOnFailure
            onFailure recordFailure
            Stage.generate
            Stage.build
            Stage.runTest
            Stage.cleanFable
        }
        Stage.echoStatus
        Stage.release generationFailures
        Stage.cleanTemp
    }
//%CliCron%END%
}
//%Cli%END%
