name: Scheduled Binding Generator
# Ensure any workflow in FAKE runs `post` cleans AFTER the test has run.
on:
  workflow_call:
  workflow_dispatch:
    branches:
      - main
      - develop
  
  # Avoid setting jobs on the hour.
  # See https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#schedule
  schedule:
    - cron: '23 4 * * 0'
  
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  NODE_VERSION: 24.x
  NUGET_KEY: ${{ secrets.FABLE_ELECTRON_NUGET }}
  # Must explicitly set GH_TOKEN for gh cli in workflows
  GH_TOKEN: ${{ github.token }}

concurrency:
  # If we call a workflow while another is scheduled; cancel
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write
  # permission to write pull requests
  pull-requests: write

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # Require fetch-depth 0 for gitnet/changelog generation
          fetch-depth: 0
      
      - name: Ownership Workaround
        run: git config --global --add safe.directory '*'
        
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache-dependency-path: ./tests/Fable.Electron.Remoting.Tests/package-lock.json
          cache: npm
        
      - name: Install Chromium
        uses: nanasess/setup-chromedriver@v2
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        
      - name: Run FAKE CI
        run: dotnet run -- cron --nuget-key ${{ env.NUGET_KEY }} --gh-key ${{ secrets.GITHUB_TOKEN }} --npm-ci
